### PR TITLE
Delete object from S3 if database save fails

### PR DESCRIPTION
**Pull request by jschlyter**

### CODE REVIEW

**Comment by eest** [comment]
Looks reasonable, 502 sounds a bit strange for storage errors (I guess the server might be considered a mongodb gateway at that point, but feels weird to me)

**Comment by jschlyter** [comment]
> Looks reasonable, 502 sounds a bit strange for storage errors (I guess the server might be considered a mongodb gateway at that point, but feels weird to me)

I've changed this to 500 in 9e6673a8fd709a7a4e6510c217c248134e342d40.

What if we fail to post to MQTT? How do we proceed? (ping @morkrost)

**Review by eest — APPROVED** [review]
LGTM

**Comment by morkrost** [comment]
MQTT can fail in two ways, you fail to send it and I fail to pay attention when it is sent. 

I check for the existence of files in S3 atm, so no need for MQTT right now, and once I start using my new job scheduler we can decide on the best strategy.

**Pull request merged**
